/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Merge1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Merge1{}

// Merge1 struct for Merge1
type Merge1 struct {
	// Optional commit message for this merge request  If not set, the server will generate a commit message automatically using metadata from the  merged commits.
	// Deprecated
	Message *string `json:"message,omitempty"`
	// The hash of the last commit to merge.  This commit must be present in the history on 'fromRefName' before the first common parent with respect to the target branch.
	FromHash *string `json:"fromHash,omitempty" validate:"regexp=^[0-9a-fA-F]{8,64}$"`
	// The name of the reference that contains the 'source' commits for the requested merge or transplant operation. 
	FromRefName string `json:"fromRefName" validate:"regexp=^(?:[A-Za-z](?:(?:(?![.][.])[A-Za-z0-9.\\/_-])*[A-Za-z0-9_-])?)|-$"`
	// Specific merge behaviour requests by content key.  The default is set by the `defaultKeyMergeMode` parameter. 
	KeyMergeModes []MergeKeyMergeModesInner `json:"keyMergeModes,omitempty"`
	// The default merge mode. If not set, `NORMAL` is assumed.  This settings applies to key thaWhen set to 'true' instructs the server to validate the request but to avoid committing any changes.t are not explicitly mentioned in the `keyMergeModes` property. 
	DefaultKeyMergeMode *string `json:"defaultKeyMergeMode,omitempty"`
	// When set to 'true' instructs the server to validate the request but to avoid committing any changes. 
	DryRun *bool `json:"dryRun,omitempty"`
	// Whether to provide optional response data. 
	FetchAdditionalInfo *bool `json:"fetchAdditionalInfo,omitempty"`
	// When set to 'true' instructs the server to produce normal (non-error) responses in case a conflict is detected and report conflict details in the response payload.
	ReturnConflictAsResult *bool `json:"returnConflictAsResult,omitempty"`
	CommitMeta *CommitMeta3 `json:"commitMeta,omitempty"`
}

type _Merge1 Merge1

// NewMerge1 instantiates a new Merge1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerge1(fromRefName string) *Merge1 {
	this := Merge1{}
	this.FromRefName = fromRefName
	return &this
}

// NewMerge1WithDefaults instantiates a new Merge1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerge1WithDefaults() *Merge1 {
	this := Merge1{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
// Deprecated
func (o *Merge1) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *Merge1) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Merge1) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
// Deprecated
func (o *Merge1) SetMessage(v string) {
	o.Message = &v
}

// GetFromHash returns the FromHash field value if set, zero value otherwise.
func (o *Merge1) GetFromHash() string {
	if o == nil || IsNil(o.FromHash) {
		var ret string
		return ret
	}
	return *o.FromHash
}

// GetFromHashOk returns a tuple with the FromHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Merge1) GetFromHashOk() (*string, bool) {
	if o == nil || IsNil(o.FromHash) {
		return nil, false
	}
	return o.FromHash, true
}

// HasFromHash returns a boolean if a field has been set.
func (o *Merge1) HasFromHash() bool {
	if o != nil && !IsNil(o.FromHash) {
		return true
	}

	return false
}

// SetFromHash gets a reference to the given string and assigns it to the FromHash field.
func (o *Merge1) SetFromHash(v string) {
	o.FromHash = &v
}

// GetFromRefName returns the FromRefName field value
func (o *Merge1) GetFromRefName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromRefName
}

// GetFromRefNameOk returns a tuple with the FromRefName field value
// and a boolean to check if the value has been set.
func (o *Merge1) GetFromRefNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromRefName, true
}

// SetFromRefName sets field value
func (o *Merge1) SetFromRefName(v string) {
	o.FromRefName = v
}

// GetKeyMergeModes returns the KeyMergeModes field value if set, zero value otherwise.
func (o *Merge1) GetKeyMergeModes() []MergeKeyMergeModesInner {
	if o == nil || IsNil(o.KeyMergeModes) {
		var ret []MergeKeyMergeModesInner
		return ret
	}
	return o.KeyMergeModes
}

// GetKeyMergeModesOk returns a tuple with the KeyMergeModes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Merge1) GetKeyMergeModesOk() ([]MergeKeyMergeModesInner, bool) {
	if o == nil || IsNil(o.KeyMergeModes) {
		return nil, false
	}
	return o.KeyMergeModes, true
}

// HasKeyMergeModes returns a boolean if a field has been set.
func (o *Merge1) HasKeyMergeModes() bool {
	if o != nil && !IsNil(o.KeyMergeModes) {
		return true
	}

	return false
}

// SetKeyMergeModes gets a reference to the given []MergeKeyMergeModesInner and assigns it to the KeyMergeModes field.
func (o *Merge1) SetKeyMergeModes(v []MergeKeyMergeModesInner) {
	o.KeyMergeModes = v
}

// GetDefaultKeyMergeMode returns the DefaultKeyMergeMode field value if set, zero value otherwise.
func (o *Merge1) GetDefaultKeyMergeMode() string {
	if o == nil || IsNil(o.DefaultKeyMergeMode) {
		var ret string
		return ret
	}
	return *o.DefaultKeyMergeMode
}

// GetDefaultKeyMergeModeOk returns a tuple with the DefaultKeyMergeMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Merge1) GetDefaultKeyMergeModeOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultKeyMergeMode) {
		return nil, false
	}
	return o.DefaultKeyMergeMode, true
}

// HasDefaultKeyMergeMode returns a boolean if a field has been set.
func (o *Merge1) HasDefaultKeyMergeMode() bool {
	if o != nil && !IsNil(o.DefaultKeyMergeMode) {
		return true
	}

	return false
}

// SetDefaultKeyMergeMode gets a reference to the given string and assigns it to the DefaultKeyMergeMode field.
func (o *Merge1) SetDefaultKeyMergeMode(v string) {
	o.DefaultKeyMergeMode = &v
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *Merge1) GetDryRun() bool {
	if o == nil || IsNil(o.DryRun) {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Merge1) GetDryRunOk() (*bool, bool) {
	if o == nil || IsNil(o.DryRun) {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *Merge1) HasDryRun() bool {
	if o != nil && !IsNil(o.DryRun) {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *Merge1) SetDryRun(v bool) {
	o.DryRun = &v
}

// GetFetchAdditionalInfo returns the FetchAdditionalInfo field value if set, zero value otherwise.
func (o *Merge1) GetFetchAdditionalInfo() bool {
	if o == nil || IsNil(o.FetchAdditionalInfo) {
		var ret bool
		return ret
	}
	return *o.FetchAdditionalInfo
}

// GetFetchAdditionalInfoOk returns a tuple with the FetchAdditionalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Merge1) GetFetchAdditionalInfoOk() (*bool, bool) {
	if o == nil || IsNil(o.FetchAdditionalInfo) {
		return nil, false
	}
	return o.FetchAdditionalInfo, true
}

// HasFetchAdditionalInfo returns a boolean if a field has been set.
func (o *Merge1) HasFetchAdditionalInfo() bool {
	if o != nil && !IsNil(o.FetchAdditionalInfo) {
		return true
	}

	return false
}

// SetFetchAdditionalInfo gets a reference to the given bool and assigns it to the FetchAdditionalInfo field.
func (o *Merge1) SetFetchAdditionalInfo(v bool) {
	o.FetchAdditionalInfo = &v
}

// GetReturnConflictAsResult returns the ReturnConflictAsResult field value if set, zero value otherwise.
func (o *Merge1) GetReturnConflictAsResult() bool {
	if o == nil || IsNil(o.ReturnConflictAsResult) {
		var ret bool
		return ret
	}
	return *o.ReturnConflictAsResult
}

// GetReturnConflictAsResultOk returns a tuple with the ReturnConflictAsResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Merge1) GetReturnConflictAsResultOk() (*bool, bool) {
	if o == nil || IsNil(o.ReturnConflictAsResult) {
		return nil, false
	}
	return o.ReturnConflictAsResult, true
}

// HasReturnConflictAsResult returns a boolean if a field has been set.
func (o *Merge1) HasReturnConflictAsResult() bool {
	if o != nil && !IsNil(o.ReturnConflictAsResult) {
		return true
	}

	return false
}

// SetReturnConflictAsResult gets a reference to the given bool and assigns it to the ReturnConflictAsResult field.
func (o *Merge1) SetReturnConflictAsResult(v bool) {
	o.ReturnConflictAsResult = &v
}

// GetCommitMeta returns the CommitMeta field value if set, zero value otherwise.
func (o *Merge1) GetCommitMeta() CommitMeta3 {
	if o == nil || IsNil(o.CommitMeta) {
		var ret CommitMeta3
		return ret
	}
	return *o.CommitMeta
}

// GetCommitMetaOk returns a tuple with the CommitMeta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Merge1) GetCommitMetaOk() (*CommitMeta3, bool) {
	if o == nil || IsNil(o.CommitMeta) {
		return nil, false
	}
	return o.CommitMeta, true
}

// HasCommitMeta returns a boolean if a field has been set.
func (o *Merge1) HasCommitMeta() bool {
	if o != nil && !IsNil(o.CommitMeta) {
		return true
	}

	return false
}

// SetCommitMeta gets a reference to the given CommitMeta3 and assigns it to the CommitMeta field.
func (o *Merge1) SetCommitMeta(v CommitMeta3) {
	o.CommitMeta = &v
}

func (o Merge1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Merge1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.FromHash) {
		toSerialize["fromHash"] = o.FromHash
	}
	toSerialize["fromRefName"] = o.FromRefName
	if !IsNil(o.KeyMergeModes) {
		toSerialize["keyMergeModes"] = o.KeyMergeModes
	}
	if !IsNil(o.DefaultKeyMergeMode) {
		toSerialize["defaultKeyMergeMode"] = o.DefaultKeyMergeMode
	}
	if !IsNil(o.DryRun) {
		toSerialize["dryRun"] = o.DryRun
	}
	if !IsNil(o.FetchAdditionalInfo) {
		toSerialize["fetchAdditionalInfo"] = o.FetchAdditionalInfo
	}
	if !IsNil(o.ReturnConflictAsResult) {
		toSerialize["returnConflictAsResult"] = o.ReturnConflictAsResult
	}
	if !IsNil(o.CommitMeta) {
		toSerialize["commitMeta"] = o.CommitMeta
	}
	return toSerialize, nil
}

func (o *Merge1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fromRefName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMerge1 := _Merge1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMerge1)

	if err != nil {
		return err
	}

	*o = Merge1(varMerge1)

	return err
}

type NullableMerge1 struct {
	value *Merge1
	isSet bool
}

func (v NullableMerge1) Get() *Merge1 {
	return v.value
}

func (v *NullableMerge1) Set(val *Merge1) {
	v.value = val
	v.isSet = true
}

func (v NullableMerge1) IsSet() bool {
	return v.isSet
}

func (v *NullableMerge1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerge1(val *Merge1) *NullableMerge1 {
	return &NullableMerge1{value: val, isSet: true}
}

func (v NullableMerge1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerge1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


