/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RepositoryConfigResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepositoryConfigResponse{}

// RepositoryConfigResponse struct for RepositoryConfigResponse
type RepositoryConfigResponse struct {
	// The existing configuration objects for the requested types will be returned. Non-existing config objects will not be returned.
	Configs []GarbageCollectorConfigObject `json:"configs,omitempty"`
}

// NewRepositoryConfigResponse instantiates a new RepositoryConfigResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepositoryConfigResponse() *RepositoryConfigResponse {
	this := RepositoryConfigResponse{}
	return &this
}

// NewRepositoryConfigResponseWithDefaults instantiates a new RepositoryConfigResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepositoryConfigResponseWithDefaults() *RepositoryConfigResponse {
	this := RepositoryConfigResponse{}
	return &this
}

// GetConfigs returns the Configs field value if set, zero value otherwise.
func (o *RepositoryConfigResponse) GetConfigs() []GarbageCollectorConfigObject {
	if o == nil || IsNil(o.Configs) {
		var ret []GarbageCollectorConfigObject
		return ret
	}
	return o.Configs
}

// GetConfigsOk returns a tuple with the Configs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryConfigResponse) GetConfigsOk() ([]GarbageCollectorConfigObject, bool) {
	if o == nil || IsNil(o.Configs) {
		return nil, false
	}
	return o.Configs, true
}

// HasConfigs returns a boolean if a field has been set.
func (o *RepositoryConfigResponse) HasConfigs() bool {
	if o != nil && !IsNil(o.Configs) {
		return true
	}

	return false
}

// SetConfigs gets a reference to the given []GarbageCollectorConfigObject and assigns it to the Configs field.
func (o *RepositoryConfigResponse) SetConfigs(v []GarbageCollectorConfigObject) {
	o.Configs = v
}

func (o RepositoryConfigResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepositoryConfigResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Configs) {
		toSerialize["configs"] = o.Configs
	}
	return toSerialize, nil
}

type NullableRepositoryConfigResponse struct {
	value *RepositoryConfigResponse
	isSet bool
}

func (v NullableRepositoryConfigResponse) Get() *RepositoryConfigResponse {
	return v.value
}

func (v *NullableRepositoryConfigResponse) Set(val *RepositoryConfigResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRepositoryConfigResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRepositoryConfigResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepositoryConfigResponse(val *RepositoryConfigResponse) *NullableRepositoryConfigResponse {
	return &NullableRepositoryConfigResponse{value: val, isSet: true}
}

func (v NullableRepositoryConfigResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepositoryConfigResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


