/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// OperationV1 - Describes an operation to be performed against one content object.  The Nessie backend will validate the correctness of the operations.
type OperationV1 struct {
	CommitResponseAddedContentsInner *CommitResponseAddedContentsInner
	DeleteContentOperationForAContentKey *DeleteContentOperationForAContentKey
	PutContentOperationForAContentKey4 *PutContentOperationForAContentKey4
}

// CommitResponseAddedContentsInnerAsOperationV1 is a convenience function that returns CommitResponseAddedContentsInner wrapped in OperationV1
func CommitResponseAddedContentsInnerAsOperationV1(v *CommitResponseAddedContentsInner) OperationV1 {
	return OperationV1{
		CommitResponseAddedContentsInner: v,
	}
}

// DeleteContentOperationForAContentKeyAsOperationV1 is a convenience function that returns DeleteContentOperationForAContentKey wrapped in OperationV1
func DeleteContentOperationForAContentKeyAsOperationV1(v *DeleteContentOperationForAContentKey) OperationV1 {
	return OperationV1{
		DeleteContentOperationForAContentKey: v,
	}
}

// PutContentOperationForAContentKey4AsOperationV1 is a convenience function that returns PutContentOperationForAContentKey4 wrapped in OperationV1
func PutContentOperationForAContentKey4AsOperationV1(v *PutContentOperationForAContentKey4) OperationV1 {
	return OperationV1{
		PutContentOperationForAContentKey4: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *OperationV1) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CommitResponseAddedContentsInner
	err = newStrictDecoder(data).Decode(&dst.CommitResponseAddedContentsInner)
	if err == nil {
		jsonCommitResponseAddedContentsInner, _ := json.Marshal(dst.CommitResponseAddedContentsInner)
		if string(jsonCommitResponseAddedContentsInner) == "{}" { // empty struct
			dst.CommitResponseAddedContentsInner = nil
		} else {
			if err = validator.Validate(dst.CommitResponseAddedContentsInner); err != nil {
				dst.CommitResponseAddedContentsInner = nil
			} else {
				match++
			}
		}
	} else {
		dst.CommitResponseAddedContentsInner = nil
	}

	// try to unmarshal data into DeleteContentOperationForAContentKey
	err = newStrictDecoder(data).Decode(&dst.DeleteContentOperationForAContentKey)
	if err == nil {
		jsonDeleteContentOperationForAContentKey, _ := json.Marshal(dst.DeleteContentOperationForAContentKey)
		if string(jsonDeleteContentOperationForAContentKey) == "{}" { // empty struct
			dst.DeleteContentOperationForAContentKey = nil
		} else {
			if err = validator.Validate(dst.DeleteContentOperationForAContentKey); err != nil {
				dst.DeleteContentOperationForAContentKey = nil
			} else {
				match++
			}
		}
	} else {
		dst.DeleteContentOperationForAContentKey = nil
	}

	// try to unmarshal data into PutContentOperationForAContentKey4
	err = newStrictDecoder(data).Decode(&dst.PutContentOperationForAContentKey4)
	if err == nil {
		jsonPutContentOperationForAContentKey4, _ := json.Marshal(dst.PutContentOperationForAContentKey4)
		if string(jsonPutContentOperationForAContentKey4) == "{}" { // empty struct
			dst.PutContentOperationForAContentKey4 = nil
		} else {
			if err = validator.Validate(dst.PutContentOperationForAContentKey4); err != nil {
				dst.PutContentOperationForAContentKey4 = nil
			} else {
				match++
			}
		}
	} else {
		dst.PutContentOperationForAContentKey4 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CommitResponseAddedContentsInner = nil
		dst.DeleteContentOperationForAContentKey = nil
		dst.PutContentOperationForAContentKey4 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(OperationV1)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(OperationV1)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src OperationV1) MarshalJSON() ([]byte, error) {
	if src.CommitResponseAddedContentsInner != nil {
		return json.Marshal(&src.CommitResponseAddedContentsInner)
	}

	if src.DeleteContentOperationForAContentKey != nil {
		return json.Marshal(&src.DeleteContentOperationForAContentKey)
	}

	if src.PutContentOperationForAContentKey4 != nil {
		return json.Marshal(&src.PutContentOperationForAContentKey4)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *OperationV1) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CommitResponseAddedContentsInner != nil {
		return obj.CommitResponseAddedContentsInner
	}

	if obj.DeleteContentOperationForAContentKey != nil {
		return obj.DeleteContentOperationForAContentKey
	}

	if obj.PutContentOperationForAContentKey4 != nil {
		return obj.PutContentOperationForAContentKey4
	}

	// all schemas are nil
	return nil
}

type NullableOperationV1 struct {
	value *OperationV1
	isSet bool
}

func (v NullableOperationV1) Get() *OperationV1 {
	return v.value
}

func (v *NullableOperationV1) Set(val *OperationV1) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationV1) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationV1(val *OperationV1) *NullableOperationV1 {
	return &NullableOperationV1{value: val, isSet: true}
}

func (v NullableOperationV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


