/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DetachedV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DetachedV1{}

// DetachedV1 struct for DetachedV1
type DetachedV1 struct {
	Hash string `json:"hash" validate:"regexp=^([0-9a-fA-F]{8,64})?((?:([~*^])([0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{1,9}Z|([0-9]+)))*)$"`
	Metadata *ReferenceMetadata1 `json:"metadata,omitempty"`
}

type _DetachedV1 DetachedV1

// NewDetachedV1 instantiates a new DetachedV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetachedV1(hash string) *DetachedV1 {
	this := DetachedV1{}
	this.Hash = hash
	return &this
}

// NewDetachedV1WithDefaults instantiates a new DetachedV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetachedV1WithDefaults() *DetachedV1 {
	this := DetachedV1{}
	return &this
}

// GetHash returns the Hash field value
func (o *DetachedV1) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *DetachedV1) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *DetachedV1) SetHash(v string) {
	o.Hash = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *DetachedV1) GetMetadata() ReferenceMetadata1 {
	if o == nil || IsNil(o.Metadata) {
		var ret ReferenceMetadata1
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetachedV1) GetMetadataOk() (*ReferenceMetadata1, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *DetachedV1) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given ReferenceMetadata1 and assigns it to the Metadata field.
func (o *DetachedV1) SetMetadata(v ReferenceMetadata1) {
	o.Metadata = &v
}

func (o DetachedV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DetachedV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hash"] = o.Hash
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *DetachedV1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hash",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDetachedV1 := _DetachedV1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDetachedV1)

	if err != nil {
		return err
	}

	*o = DetachedV1(varDetachedV1)

	return err
}

type NullableDetachedV1 struct {
	value *DetachedV1
	isSet bool
}

func (v NullableDetachedV1) Get() *DetachedV1 {
	return v.value
}

func (v *NullableDetachedV1) Set(val *DetachedV1) {
	v.value = val
	v.isSet = true
}

func (v NullableDetachedV1) IsSet() bool {
	return v.isSet
}

func (v *NullableDetachedV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetachedV1(val *DetachedV1) *NullableDetachedV1 {
	return &NullableDetachedV1{value: val, isSet: true}
}

func (v NullableDetachedV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetachedV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


