/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NamespaceV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NamespaceV2{}

// NamespaceV2 struct for NamespaceV2
type NamespaceV2 struct {
	Id *string `json:"id,omitempty"`
	Elements []string `json:"elements"`
	Properties map[string]string `json:"properties"`
}

type _NamespaceV2 NamespaceV2

// NewNamespaceV2 instantiates a new NamespaceV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNamespaceV2(elements []string, properties map[string]string) *NamespaceV2 {
	this := NamespaceV2{}
	this.Elements = elements
	this.Properties = properties
	return &this
}

// NewNamespaceV2WithDefaults instantiates a new NamespaceV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNamespaceV2WithDefaults() *NamespaceV2 {
	this := NamespaceV2{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NamespaceV2) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamespaceV2) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NamespaceV2) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NamespaceV2) SetId(v string) {
	o.Id = &v
}

// GetElements returns the Elements field value
func (o *NamespaceV2) GetElements() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Elements
}

// GetElementsOk returns a tuple with the Elements field value
// and a boolean to check if the value has been set.
func (o *NamespaceV2) GetElementsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Elements, true
}

// SetElements sets field value
func (o *NamespaceV2) SetElements(v []string) {
	o.Elements = v
}

// GetProperties returns the Properties field value
func (o *NamespaceV2) GetProperties() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *NamespaceV2) GetPropertiesOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Properties, true
}

// SetProperties sets field value
func (o *NamespaceV2) SetProperties(v map[string]string) {
	o.Properties = v
}

func (o NamespaceV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NamespaceV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["elements"] = o.Elements
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *NamespaceV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"elements",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNamespaceV2 := _NamespaceV2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNamespaceV2)

	if err != nil {
		return err
	}

	*o = NamespaceV2(varNamespaceV2)

	return err
}

type NullableNamespaceV2 struct {
	value *NamespaceV2
	isSet bool
}

func (v NullableNamespaceV2) Get() *NamespaceV2 {
	return v.value
}

func (v *NullableNamespaceV2) Set(val *NamespaceV2) {
	v.value = val
	v.isSet = true
}

func (v NullableNamespaceV2) IsSet() bool {
	return v.isSet
}

func (v *NullableNamespaceV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNamespaceV2(val *NamespaceV2) *NullableNamespaceV2 {
	return &NullableNamespaceV2{value: val, isSet: true}
}

func (v NullableNamespaceV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNamespaceV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


