/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Documentation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Documentation{}

// Documentation struct for Documentation
type Documentation struct {
	MimeType string `json:"mimeType"`
	Text string `json:"text"`
}

type _Documentation Documentation

// NewDocumentation instantiates a new Documentation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentation(mimeType string, text string) *Documentation {
	this := Documentation{}
	this.MimeType = mimeType
	this.Text = text
	return &this
}

// NewDocumentationWithDefaults instantiates a new Documentation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentationWithDefaults() *Documentation {
	this := Documentation{}
	return &this
}

// GetMimeType returns the MimeType field value
func (o *Documentation) GetMimeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MimeType
}

// GetMimeTypeOk returns a tuple with the MimeType field value
// and a boolean to check if the value has been set.
func (o *Documentation) GetMimeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MimeType, true
}

// SetMimeType sets field value
func (o *Documentation) SetMimeType(v string) {
	o.MimeType = v
}

// GetText returns the Text field value
func (o *Documentation) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *Documentation) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *Documentation) SetText(v string) {
	o.Text = v
}

func (o Documentation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Documentation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mimeType"] = o.MimeType
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *Documentation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mimeType",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDocumentation := _Documentation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDocumentation)

	if err != nil {
		return err
	}

	*o = Documentation(varDocumentation)

	return err
}

type NullableDocumentation struct {
	value *Documentation
	isSet bool
}

func (v NullableDocumentation) Get() *Documentation {
	return v.value
}

func (v *NullableDocumentation) Set(val *Documentation) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentation) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentation(val *Documentation) *NullableDocumentation {
	return &NullableDocumentation{value: val, isSet: true}
}

func (v NullableDocumentation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


