/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteContentOperationForAContentKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteContentOperationForAContentKey{}

// DeleteContentOperationForAContentKey Used to delete an existing content key.  If the key for a content shall change (aka a rename), then use a `Delete` operation using the current (old) key and a `Put` operation using the new key with the current `Content` in the the `value` field. See `Put` operation.
type DeleteContentOperationForAContentKey struct {
	Key AddedContentKey `json:"key"`
}

type _DeleteContentOperationForAContentKey DeleteContentOperationForAContentKey

// NewDeleteContentOperationForAContentKey instantiates a new DeleteContentOperationForAContentKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteContentOperationForAContentKey(key AddedContentKey) *DeleteContentOperationForAContentKey {
	this := DeleteContentOperationForAContentKey{}
	this.Key = key
	return &this
}

// NewDeleteContentOperationForAContentKeyWithDefaults instantiates a new DeleteContentOperationForAContentKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteContentOperationForAContentKeyWithDefaults() *DeleteContentOperationForAContentKey {
	this := DeleteContentOperationForAContentKey{}
	return &this
}

// GetKey returns the Key field value
func (o *DeleteContentOperationForAContentKey) GetKey() AddedContentKey {
	if o == nil {
		var ret AddedContentKey
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *DeleteContentOperationForAContentKey) GetKeyOk() (*AddedContentKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *DeleteContentOperationForAContentKey) SetKey(v AddedContentKey) {
	o.Key = v
}

func (o DeleteContentOperationForAContentKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteContentOperationForAContentKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

func (o *DeleteContentOperationForAContentKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteContentOperationForAContentKey := _DeleteContentOperationForAContentKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteContentOperationForAContentKey)

	if err != nil {
		return err
	}

	*o = DeleteContentOperationForAContentKey(varDeleteContentOperationForAContentKey)

	return err
}

type NullableDeleteContentOperationForAContentKey struct {
	value *DeleteContentOperationForAContentKey
	isSet bool
}

func (v NullableDeleteContentOperationForAContentKey) Get() *DeleteContentOperationForAContentKey {
	return v.value
}

func (v *NullableDeleteContentOperationForAContentKey) Set(val *DeleteContentOperationForAContentKey) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteContentOperationForAContentKey) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteContentOperationForAContentKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteContentOperationForAContentKey(val *DeleteContentOperationForAContentKey) *NullableDeleteContentOperationForAContentKey {
	return &NullableDeleteContentOperationForAContentKey{value: val, isSet: true}
}

func (v NullableDeleteContentOperationForAContentKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteContentOperationForAContentKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


