/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the NessieConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NessieConfiguration{}

// NessieConfiguration Configuration object to tell a client how a server is configured.
type NessieConfiguration struct {
	DefaultBranch *string `json:"defaultBranch,omitempty"`
	MinSupportedApiVersion *int32 `json:"minSupportedApiVersion,omitempty"`
	MaxSupportedApiVersion *int32 `json:"maxSupportedApiVersion,omitempty"`
	ActualApiVersion *int32 `json:"actualApiVersion,omitempty"`
	// Semver version representing the behavior of the Nessie server.  Additional functionality might be added to Nessie servers within a \"spec major version\" in a non-breaking way. Clients are encouraged to check the spec version when using such added functionality.
	SpecVersion *string `json:"specVersion,omitempty"`
	NoAncestorHash *string `json:"noAncestorHash,omitempty"`
	RepositoryCreationTimestamp *time.Time `json:"repositoryCreationTimestamp,omitempty"`
	OldestPossibleCommitTimestamp *time.Time `json:"oldestPossibleCommitTimestamp,omitempty"`
	AdditionalPropertiesField map[string]string `json:"additionalProperties,omitempty"`
}

// NewNessieConfiguration instantiates a new NessieConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNessieConfiguration() *NessieConfiguration {
	this := NessieConfiguration{}
	return &this
}

// NewNessieConfigurationWithDefaults instantiates a new NessieConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNessieConfigurationWithDefaults() *NessieConfiguration {
	this := NessieConfiguration{}
	return &this
}

// GetDefaultBranch returns the DefaultBranch field value if set, zero value otherwise.
func (o *NessieConfiguration) GetDefaultBranch() string {
	if o == nil || IsNil(o.DefaultBranch) {
		var ret string
		return ret
	}
	return *o.DefaultBranch
}

// GetDefaultBranchOk returns a tuple with the DefaultBranch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NessieConfiguration) GetDefaultBranchOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultBranch) {
		return nil, false
	}
	return o.DefaultBranch, true
}

// HasDefaultBranch returns a boolean if a field has been set.
func (o *NessieConfiguration) HasDefaultBranch() bool {
	if o != nil && !IsNil(o.DefaultBranch) {
		return true
	}

	return false
}

// SetDefaultBranch gets a reference to the given string and assigns it to the DefaultBranch field.
func (o *NessieConfiguration) SetDefaultBranch(v string) {
	o.DefaultBranch = &v
}

// GetMinSupportedApiVersion returns the MinSupportedApiVersion field value if set, zero value otherwise.
func (o *NessieConfiguration) GetMinSupportedApiVersion() int32 {
	if o == nil || IsNil(o.MinSupportedApiVersion) {
		var ret int32
		return ret
	}
	return *o.MinSupportedApiVersion
}

// GetMinSupportedApiVersionOk returns a tuple with the MinSupportedApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NessieConfiguration) GetMinSupportedApiVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.MinSupportedApiVersion) {
		return nil, false
	}
	return o.MinSupportedApiVersion, true
}

// HasMinSupportedApiVersion returns a boolean if a field has been set.
func (o *NessieConfiguration) HasMinSupportedApiVersion() bool {
	if o != nil && !IsNil(o.MinSupportedApiVersion) {
		return true
	}

	return false
}

// SetMinSupportedApiVersion gets a reference to the given int32 and assigns it to the MinSupportedApiVersion field.
func (o *NessieConfiguration) SetMinSupportedApiVersion(v int32) {
	o.MinSupportedApiVersion = &v
}

// GetMaxSupportedApiVersion returns the MaxSupportedApiVersion field value if set, zero value otherwise.
func (o *NessieConfiguration) GetMaxSupportedApiVersion() int32 {
	if o == nil || IsNil(o.MaxSupportedApiVersion) {
		var ret int32
		return ret
	}
	return *o.MaxSupportedApiVersion
}

// GetMaxSupportedApiVersionOk returns a tuple with the MaxSupportedApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NessieConfiguration) GetMaxSupportedApiVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxSupportedApiVersion) {
		return nil, false
	}
	return o.MaxSupportedApiVersion, true
}

// HasMaxSupportedApiVersion returns a boolean if a field has been set.
func (o *NessieConfiguration) HasMaxSupportedApiVersion() bool {
	if o != nil && !IsNil(o.MaxSupportedApiVersion) {
		return true
	}

	return false
}

// SetMaxSupportedApiVersion gets a reference to the given int32 and assigns it to the MaxSupportedApiVersion field.
func (o *NessieConfiguration) SetMaxSupportedApiVersion(v int32) {
	o.MaxSupportedApiVersion = &v
}

// GetActualApiVersion returns the ActualApiVersion field value if set, zero value otherwise.
func (o *NessieConfiguration) GetActualApiVersion() int32 {
	if o == nil || IsNil(o.ActualApiVersion) {
		var ret int32
		return ret
	}
	return *o.ActualApiVersion
}

// GetActualApiVersionOk returns a tuple with the ActualApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NessieConfiguration) GetActualApiVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.ActualApiVersion) {
		return nil, false
	}
	return o.ActualApiVersion, true
}

// HasActualApiVersion returns a boolean if a field has been set.
func (o *NessieConfiguration) HasActualApiVersion() bool {
	if o != nil && !IsNil(o.ActualApiVersion) {
		return true
	}

	return false
}

// SetActualApiVersion gets a reference to the given int32 and assigns it to the ActualApiVersion field.
func (o *NessieConfiguration) SetActualApiVersion(v int32) {
	o.ActualApiVersion = &v
}

// GetSpecVersion returns the SpecVersion field value if set, zero value otherwise.
func (o *NessieConfiguration) GetSpecVersion() string {
	if o == nil || IsNil(o.SpecVersion) {
		var ret string
		return ret
	}
	return *o.SpecVersion
}

// GetSpecVersionOk returns a tuple with the SpecVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NessieConfiguration) GetSpecVersionOk() (*string, bool) {
	if o == nil || IsNil(o.SpecVersion) {
		return nil, false
	}
	return o.SpecVersion, true
}

// HasSpecVersion returns a boolean if a field has been set.
func (o *NessieConfiguration) HasSpecVersion() bool {
	if o != nil && !IsNil(o.SpecVersion) {
		return true
	}

	return false
}

// SetSpecVersion gets a reference to the given string and assigns it to the SpecVersion field.
func (o *NessieConfiguration) SetSpecVersion(v string) {
	o.SpecVersion = &v
}

// GetNoAncestorHash returns the NoAncestorHash field value if set, zero value otherwise.
func (o *NessieConfiguration) GetNoAncestorHash() string {
	if o == nil || IsNil(o.NoAncestorHash) {
		var ret string
		return ret
	}
	return *o.NoAncestorHash
}

// GetNoAncestorHashOk returns a tuple with the NoAncestorHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NessieConfiguration) GetNoAncestorHashOk() (*string, bool) {
	if o == nil || IsNil(o.NoAncestorHash) {
		return nil, false
	}
	return o.NoAncestorHash, true
}

// HasNoAncestorHash returns a boolean if a field has been set.
func (o *NessieConfiguration) HasNoAncestorHash() bool {
	if o != nil && !IsNil(o.NoAncestorHash) {
		return true
	}

	return false
}

// SetNoAncestorHash gets a reference to the given string and assigns it to the NoAncestorHash field.
func (o *NessieConfiguration) SetNoAncestorHash(v string) {
	o.NoAncestorHash = &v
}

// GetRepositoryCreationTimestamp returns the RepositoryCreationTimestamp field value if set, zero value otherwise.
func (o *NessieConfiguration) GetRepositoryCreationTimestamp() time.Time {
	if o == nil || IsNil(o.RepositoryCreationTimestamp) {
		var ret time.Time
		return ret
	}
	return *o.RepositoryCreationTimestamp
}

// GetRepositoryCreationTimestampOk returns a tuple with the RepositoryCreationTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NessieConfiguration) GetRepositoryCreationTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RepositoryCreationTimestamp) {
		return nil, false
	}
	return o.RepositoryCreationTimestamp, true
}

// HasRepositoryCreationTimestamp returns a boolean if a field has been set.
func (o *NessieConfiguration) HasRepositoryCreationTimestamp() bool {
	if o != nil && !IsNil(o.RepositoryCreationTimestamp) {
		return true
	}

	return false
}

// SetRepositoryCreationTimestamp gets a reference to the given time.Time and assigns it to the RepositoryCreationTimestamp field.
func (o *NessieConfiguration) SetRepositoryCreationTimestamp(v time.Time) {
	o.RepositoryCreationTimestamp = &v
}

// GetOldestPossibleCommitTimestamp returns the OldestPossibleCommitTimestamp field value if set, zero value otherwise.
func (o *NessieConfiguration) GetOldestPossibleCommitTimestamp() time.Time {
	if o == nil || IsNil(o.OldestPossibleCommitTimestamp) {
		var ret time.Time
		return ret
	}
	return *o.OldestPossibleCommitTimestamp
}

// GetOldestPossibleCommitTimestampOk returns a tuple with the OldestPossibleCommitTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NessieConfiguration) GetOldestPossibleCommitTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.OldestPossibleCommitTimestamp) {
		return nil, false
	}
	return o.OldestPossibleCommitTimestamp, true
}

// HasOldestPossibleCommitTimestamp returns a boolean if a field has been set.
func (o *NessieConfiguration) HasOldestPossibleCommitTimestamp() bool {
	if o != nil && !IsNil(o.OldestPossibleCommitTimestamp) {
		return true
	}

	return false
}

// SetOldestPossibleCommitTimestamp gets a reference to the given time.Time and assigns it to the OldestPossibleCommitTimestamp field.
func (o *NessieConfiguration) SetOldestPossibleCommitTimestamp(v time.Time) {
	o.OldestPossibleCommitTimestamp = &v
}

// GetAdditionalPropertiesField returns the AdditionalPropertiesField field value if set, zero value otherwise.
func (o *NessieConfiguration) GetAdditionalPropertiesField() map[string]string {
	if o == nil || IsNil(o.AdditionalPropertiesField) {
		var ret map[string]string
		return ret
	}
	return o.AdditionalPropertiesField
}

// GetAdditionalPropertiesFieldOk returns a tuple with the AdditionalPropertiesField field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NessieConfiguration) GetAdditionalPropertiesFieldOk() (map[string]string, bool) {
	if o == nil || IsNil(o.AdditionalPropertiesField) {
		return map[string]string{}, false
	}
	return o.AdditionalPropertiesField, true
}

// HasAdditionalPropertiesField returns a boolean if a field has been set.
func (o *NessieConfiguration) HasAdditionalPropertiesField() bool {
	if o != nil && !IsNil(o.AdditionalPropertiesField) {
		return true
	}

	return false
}

// SetAdditionalPropertiesField gets a reference to the given map[string]string and assigns it to the AdditionalPropertiesField field.
func (o *NessieConfiguration) SetAdditionalPropertiesField(v map[string]string) {
	o.AdditionalPropertiesField = v
}

func (o NessieConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NessieConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DefaultBranch) {
		toSerialize["defaultBranch"] = o.DefaultBranch
	}
	if !IsNil(o.MinSupportedApiVersion) {
		toSerialize["minSupportedApiVersion"] = o.MinSupportedApiVersion
	}
	if !IsNil(o.MaxSupportedApiVersion) {
		toSerialize["maxSupportedApiVersion"] = o.MaxSupportedApiVersion
	}
	if !IsNil(o.ActualApiVersion) {
		toSerialize["actualApiVersion"] = o.ActualApiVersion
	}
	if !IsNil(o.SpecVersion) {
		toSerialize["specVersion"] = o.SpecVersion
	}
	if !IsNil(o.NoAncestorHash) {
		toSerialize["noAncestorHash"] = o.NoAncestorHash
	}
	if !IsNil(o.RepositoryCreationTimestamp) {
		toSerialize["repositoryCreationTimestamp"] = o.RepositoryCreationTimestamp
	}
	if !IsNil(o.OldestPossibleCommitTimestamp) {
		toSerialize["oldestPossibleCommitTimestamp"] = o.OldestPossibleCommitTimestamp
	}
	if !IsNil(o.AdditionalPropertiesField) {
		toSerialize["additionalProperties"] = o.AdditionalPropertiesField
	}
	return toSerialize, nil
}

type NullableNessieConfiguration struct {
	value *NessieConfiguration
	isSet bool
}

func (v NullableNessieConfiguration) Get() *NessieConfiguration {
	return v.value
}

func (v *NullableNessieConfiguration) Set(val *NessieConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableNessieConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableNessieConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNessieConfiguration(val *NessieConfiguration) *NullableNessieConfiguration {
	return &NullableNessieConfiguration{value: val, isSet: true}
}

func (v NullableNessieConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNessieConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


