/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Content10 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Content10{}

// Content10 struct for Content10
type Content10 struct {
	Id *string `json:"id,omitempty"`
}

// NewContent10 instantiates a new Content10 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContent10() *Content10 {
	this := Content10{}
	return &this
}

// NewContent10WithDefaults instantiates a new Content10 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContent10WithDefaults() *Content10 {
	this := Content10{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Content10) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Content10) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Content10) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Content10) SetId(v string) {
	o.Id = &v
}

func (o Content10) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Content10) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableContent10 struct {
	value *Content10
	isSet bool
}

func (v NullableContent10) Get() *Content10 {
	return v.value
}

func (v *NullableContent10) Set(val *Content10) {
	v.value = val
	v.isSet = true
}

func (v NullableContent10) IsSet() bool {
	return v.isSet
}

func (v *NullableContent10) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContent10(val *Content10) *NullableContent10 {
	return &NullableContent10{value: val, isSet: true}
}

func (v NullableContent10) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContent10) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


