/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Delete type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Delete{}

// Delete Used to delete an existing content key.  If the key for a content shall change (aka a rename), then use a `Delete` operation using the current (old) key and a `Put` operation using the new key with the current `Content` in the the `value` field. See `Put` operation.
type Delete struct {
	Key AddedContentKey `json:"key"`
}

type _Delete Delete

// NewDelete instantiates a new Delete object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDelete(key AddedContentKey) *Delete {
	this := Delete{}
	this.Key = key
	return &this
}

// NewDeleteWithDefaults instantiates a new Delete object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteWithDefaults() *Delete {
	this := Delete{}
	return &this
}

// GetKey returns the Key field value
func (o *Delete) GetKey() AddedContentKey {
	if o == nil {
		var ret AddedContentKey
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *Delete) GetKeyOk() (*AddedContentKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *Delete) SetKey(v AddedContentKey) {
	o.Key = v
}

func (o Delete) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Delete) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

func (o *Delete) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDelete := _Delete{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDelete)

	if err != nil {
		return err
	}

	*o = Delete(varDelete)

	return err
}

type NullableDelete struct {
	value *Delete
	isSet bool
}

func (v NullableDelete) Get() *Delete {
	return v.value
}

func (v *NullableDelete) Set(val *Delete) {
	v.value = val
	v.isSet = true
}

func (v NullableDelete) IsSet() bool {
	return v.isSet
}

func (v *NullableDelete) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDelete(val *Delete) *NullableDelete {
	return &NullableDelete{value: val, isSet: true}
}

func (v NullableDelete) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDelete) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


