/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Content1AnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Content1AnyOf{}

// Content1AnyOf struct for Content1AnyOf
type Content1AnyOf struct {
	Id *string `json:"id,omitempty"`
	MetadataLocation string `json:"metadataLocation" validate:"regexp=\\\\S"`
	VersionId *int64 `json:"versionId,omitempty"`
	SchemaId *int32 `json:"schemaId,omitempty"`
	// Deprecated
	SqlText string `json:"sqlText" validate:"regexp=\\\\S"`
	// Deprecated
	Dialect *string `json:"dialect,omitempty"`
}

type _Content1AnyOf Content1AnyOf

// NewContent1AnyOf instantiates a new Content1AnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContent1AnyOf(metadataLocation string, sqlText string) *Content1AnyOf {
	this := Content1AnyOf{}
	this.MetadataLocation = metadataLocation
	this.SqlText = sqlText
	return &this
}

// NewContent1AnyOfWithDefaults instantiates a new Content1AnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContent1AnyOfWithDefaults() *Content1AnyOf {
	this := Content1AnyOf{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Content1AnyOf) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Content1AnyOf) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Content1AnyOf) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Content1AnyOf) SetId(v string) {
	o.Id = &v
}

// GetMetadataLocation returns the MetadataLocation field value
func (o *Content1AnyOf) GetMetadataLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MetadataLocation
}

// GetMetadataLocationOk returns a tuple with the MetadataLocation field value
// and a boolean to check if the value has been set.
func (o *Content1AnyOf) GetMetadataLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetadataLocation, true
}

// SetMetadataLocation sets field value
func (o *Content1AnyOf) SetMetadataLocation(v string) {
	o.MetadataLocation = v
}

// GetVersionId returns the VersionId field value if set, zero value otherwise.
func (o *Content1AnyOf) GetVersionId() int64 {
	if o == nil || IsNil(o.VersionId) {
		var ret int64
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Content1AnyOf) GetVersionIdOk() (*int64, bool) {
	if o == nil || IsNil(o.VersionId) {
		return nil, false
	}
	return o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *Content1AnyOf) HasVersionId() bool {
	if o != nil && !IsNil(o.VersionId) {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given int64 and assigns it to the VersionId field.
func (o *Content1AnyOf) SetVersionId(v int64) {
	o.VersionId = &v
}

// GetSchemaId returns the SchemaId field value if set, zero value otherwise.
func (o *Content1AnyOf) GetSchemaId() int32 {
	if o == nil || IsNil(o.SchemaId) {
		var ret int32
		return ret
	}
	return *o.SchemaId
}

// GetSchemaIdOk returns a tuple with the SchemaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Content1AnyOf) GetSchemaIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SchemaId) {
		return nil, false
	}
	return o.SchemaId, true
}

// HasSchemaId returns a boolean if a field has been set.
func (o *Content1AnyOf) HasSchemaId() bool {
	if o != nil && !IsNil(o.SchemaId) {
		return true
	}

	return false
}

// SetSchemaId gets a reference to the given int32 and assigns it to the SchemaId field.
func (o *Content1AnyOf) SetSchemaId(v int32) {
	o.SchemaId = &v
}

// GetSqlText returns the SqlText field value
// Deprecated
func (o *Content1AnyOf) GetSqlText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SqlText
}

// GetSqlTextOk returns a tuple with the SqlText field value
// and a boolean to check if the value has been set.
// Deprecated
func (o *Content1AnyOf) GetSqlTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SqlText, true
}

// SetSqlText sets field value
// Deprecated
func (o *Content1AnyOf) SetSqlText(v string) {
	o.SqlText = v
}

// GetDialect returns the Dialect field value if set, zero value otherwise.
// Deprecated
func (o *Content1AnyOf) GetDialect() string {
	if o == nil || IsNil(o.Dialect) {
		var ret string
		return ret
	}
	return *o.Dialect
}

// GetDialectOk returns a tuple with the Dialect field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *Content1AnyOf) GetDialectOk() (*string, bool) {
	if o == nil || IsNil(o.Dialect) {
		return nil, false
	}
	return o.Dialect, true
}

// HasDialect returns a boolean if a field has been set.
func (o *Content1AnyOf) HasDialect() bool {
	if o != nil && !IsNil(o.Dialect) {
		return true
	}

	return false
}

// SetDialect gets a reference to the given string and assigns it to the Dialect field.
// Deprecated
func (o *Content1AnyOf) SetDialect(v string) {
	o.Dialect = &v
}

func (o Content1AnyOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Content1AnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["metadataLocation"] = o.MetadataLocation
	if !IsNil(o.VersionId) {
		toSerialize["versionId"] = o.VersionId
	}
	if !IsNil(o.SchemaId) {
		toSerialize["schemaId"] = o.SchemaId
	}
	toSerialize["sqlText"] = o.SqlText
	if !IsNil(o.Dialect) {
		toSerialize["dialect"] = o.Dialect
	}
	return toSerialize, nil
}

func (o *Content1AnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metadataLocation",
		"sqlText",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContent1AnyOf := _Content1AnyOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContent1AnyOf)

	if err != nil {
		return err
	}

	*o = Content1AnyOf(varContent1AnyOf)

	return err
}

type NullableContent1AnyOf struct {
	value *Content1AnyOf
	isSet bool
}

func (v NullableContent1AnyOf) Get() *Content1AnyOf {
	return v.value
}

func (v *NullableContent1AnyOf) Set(val *Content1AnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableContent1AnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableContent1AnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContent1AnyOf(val *Content1AnyOf) *NullableContent1AnyOf {
	return &NullableContent1AnyOf{value: val, isSet: true}
}

func (v NullableContent1AnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContent1AnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


