/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EntriesResponseV1EntriesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntriesResponseV1EntriesInner{}

// EntriesResponseV1EntriesInner struct for EntriesResponseV1EntriesInner
type EntriesResponseV1EntriesInner struct {
	// Declares the type of a Nessie content object, which is currently one of ICEBERG_TABLE, DELTA_LAKE_TABLE, ICEBERG_VIEW, NAMESPACE or UDF, which are the discriminator mapping values of the 'Content' type.
	Type *string `json:"type,omitempty"`
	Name AddedContentKey `json:"name"`
}

type _EntriesResponseV1EntriesInner EntriesResponseV1EntriesInner

// NewEntriesResponseV1EntriesInner instantiates a new EntriesResponseV1EntriesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntriesResponseV1EntriesInner(name AddedContentKey) *EntriesResponseV1EntriesInner {
	this := EntriesResponseV1EntriesInner{}
	this.Name = name
	return &this
}

// NewEntriesResponseV1EntriesInnerWithDefaults instantiates a new EntriesResponseV1EntriesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntriesResponseV1EntriesInnerWithDefaults() *EntriesResponseV1EntriesInner {
	this := EntriesResponseV1EntriesInner{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *EntriesResponseV1EntriesInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntriesResponseV1EntriesInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *EntriesResponseV1EntriesInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *EntriesResponseV1EntriesInner) SetType(v string) {
	o.Type = &v
}

// GetName returns the Name field value
func (o *EntriesResponseV1EntriesInner) GetName() AddedContentKey {
	if o == nil {
		var ret AddedContentKey
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EntriesResponseV1EntriesInner) GetNameOk() (*AddedContentKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EntriesResponseV1EntriesInner) SetName(v AddedContentKey) {
	o.Name = v
}

func (o EntriesResponseV1EntriesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntriesResponseV1EntriesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *EntriesResponseV1EntriesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntriesResponseV1EntriesInner := _EntriesResponseV1EntriesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEntriesResponseV1EntriesInner)

	if err != nil {
		return err
	}

	*o = EntriesResponseV1EntriesInner(varEntriesResponseV1EntriesInner)

	return err
}

type NullableEntriesResponseV1EntriesInner struct {
	value *EntriesResponseV1EntriesInner
	isSet bool
}

func (v NullableEntriesResponseV1EntriesInner) Get() *EntriesResponseV1EntriesInner {
	return v.value
}

func (v *NullableEntriesResponseV1EntriesInner) Set(val *EntriesResponseV1EntriesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableEntriesResponseV1EntriesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableEntriesResponseV1EntriesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntriesResponseV1EntriesInner(val *EntriesResponseV1EntriesInner) *NullableEntriesResponseV1EntriesInner {
	return &NullableEntriesResponseV1EntriesInner{value: val, isSet: true}
}

func (v NullableEntriesResponseV1EntriesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntriesResponseV1EntriesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


