/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DiffEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiffEntry{}

// DiffEntry struct for DiffEntry
type DiffEntry struct {
	Key *AddedContentKey `json:"key,omitempty"`
	From *Content2 `json:"from,omitempty"`
	To *Content2 `json:"to,omitempty"`
}

// NewDiffEntry instantiates a new DiffEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiffEntry() *DiffEntry {
	this := DiffEntry{}
	return &this
}

// NewDiffEntryWithDefaults instantiates a new DiffEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiffEntryWithDefaults() *DiffEntry {
	this := DiffEntry{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *DiffEntry) GetKey() AddedContentKey {
	if o == nil || IsNil(o.Key) {
		var ret AddedContentKey
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiffEntry) GetKeyOk() (*AddedContentKey, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *DiffEntry) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given AddedContentKey and assigns it to the Key field.
func (o *DiffEntry) SetKey(v AddedContentKey) {
	o.Key = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *DiffEntry) GetFrom() Content2 {
	if o == nil || IsNil(o.From) {
		var ret Content2
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiffEntry) GetFromOk() (*Content2, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *DiffEntry) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given Content2 and assigns it to the From field.
func (o *DiffEntry) SetFrom(v Content2) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *DiffEntry) GetTo() Content2 {
	if o == nil || IsNil(o.To) {
		var ret Content2
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiffEntry) GetToOk() (*Content2, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *DiffEntry) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given Content2 and assigns it to the To field.
func (o *DiffEntry) SetTo(v Content2) {
	o.To = &v
}

func (o DiffEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiffEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	return toSerialize, nil
}

type NullableDiffEntry struct {
	value *DiffEntry
	isSet bool
}

func (v NullableDiffEntry) Get() *DiffEntry {
	return v.value
}

func (v *NullableDiffEntry) Set(val *DiffEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableDiffEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableDiffEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiffEntry(val *DiffEntry) *NullableDiffEntry {
	return &NullableDiffEntry{value: val, isSet: true}
}

func (v NullableDiffEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiffEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


