/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContentAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentAnyOf{}

// ContentAnyOf struct for ContentAnyOf
type ContentAnyOf struct {
	Id *string `json:"id,omitempty"`
	MetadataLocationHistory []string `json:"metadataLocationHistory"`
	CheckpointLocationHistory []string `json:"checkpointLocationHistory"`
	LastCheckpoint *string `json:"lastCheckpoint,omitempty"`
}

type _ContentAnyOf ContentAnyOf

// NewContentAnyOf instantiates a new ContentAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentAnyOf(metadataLocationHistory []string, checkpointLocationHistory []string) *ContentAnyOf {
	this := ContentAnyOf{}
	this.MetadataLocationHistory = metadataLocationHistory
	this.CheckpointLocationHistory = checkpointLocationHistory
	return &this
}

// NewContentAnyOfWithDefaults instantiates a new ContentAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentAnyOfWithDefaults() *ContentAnyOf {
	this := ContentAnyOf{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ContentAnyOf) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentAnyOf) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ContentAnyOf) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ContentAnyOf) SetId(v string) {
	o.Id = &v
}

// GetMetadataLocationHistory returns the MetadataLocationHistory field value
func (o *ContentAnyOf) GetMetadataLocationHistory() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.MetadataLocationHistory
}

// GetMetadataLocationHistoryOk returns a tuple with the MetadataLocationHistory field value
// and a boolean to check if the value has been set.
func (o *ContentAnyOf) GetMetadataLocationHistoryOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MetadataLocationHistory, true
}

// SetMetadataLocationHistory sets field value
func (o *ContentAnyOf) SetMetadataLocationHistory(v []string) {
	o.MetadataLocationHistory = v
}

// GetCheckpointLocationHistory returns the CheckpointLocationHistory field value
func (o *ContentAnyOf) GetCheckpointLocationHistory() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.CheckpointLocationHistory
}

// GetCheckpointLocationHistoryOk returns a tuple with the CheckpointLocationHistory field value
// and a boolean to check if the value has been set.
func (o *ContentAnyOf) GetCheckpointLocationHistoryOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CheckpointLocationHistory, true
}

// SetCheckpointLocationHistory sets field value
func (o *ContentAnyOf) SetCheckpointLocationHistory(v []string) {
	o.CheckpointLocationHistory = v
}

// GetLastCheckpoint returns the LastCheckpoint field value if set, zero value otherwise.
func (o *ContentAnyOf) GetLastCheckpoint() string {
	if o == nil || IsNil(o.LastCheckpoint) {
		var ret string
		return ret
	}
	return *o.LastCheckpoint
}

// GetLastCheckpointOk returns a tuple with the LastCheckpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentAnyOf) GetLastCheckpointOk() (*string, bool) {
	if o == nil || IsNil(o.LastCheckpoint) {
		return nil, false
	}
	return o.LastCheckpoint, true
}

// HasLastCheckpoint returns a boolean if a field has been set.
func (o *ContentAnyOf) HasLastCheckpoint() bool {
	if o != nil && !IsNil(o.LastCheckpoint) {
		return true
	}

	return false
}

// SetLastCheckpoint gets a reference to the given string and assigns it to the LastCheckpoint field.
func (o *ContentAnyOf) SetLastCheckpoint(v string) {
	o.LastCheckpoint = &v
}

func (o ContentAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["metadataLocationHistory"] = o.MetadataLocationHistory
	toSerialize["checkpointLocationHistory"] = o.CheckpointLocationHistory
	if !IsNil(o.LastCheckpoint) {
		toSerialize["lastCheckpoint"] = o.LastCheckpoint
	}
	return toSerialize, nil
}

func (o *ContentAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metadataLocationHistory",
		"checkpointLocationHistory",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContentAnyOf := _ContentAnyOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContentAnyOf)

	if err != nil {
		return err
	}

	*o = ContentAnyOf(varContentAnyOf)

	return err
}

type NullableContentAnyOf struct {
	value *ContentAnyOf
	isSet bool
}

func (v NullableContentAnyOf) Get() *ContentAnyOf {
	return v.value
}

func (v *NullableContentAnyOf) Set(val *ContentAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableContentAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableContentAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentAnyOf(val *ContentAnyOf) *NullableContentAnyOf {
	return &NullableContentAnyOf{value: val, isSet: true}
}

func (v NullableContentAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


