/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContentWithKeyV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentWithKeyV2{}

// ContentWithKeyV2 struct for ContentWithKeyV2
type ContentWithKeyV2 struct {
	Key GetMultipleContentsRequest1RequestedKeysInner `json:"key"`
	Content Content5 `json:"content"`
	Documentation *PutContentOperationForAContentKeyDocumentation `json:"documentation,omitempty"`
}

type _ContentWithKeyV2 ContentWithKeyV2

// NewContentWithKeyV2 instantiates a new ContentWithKeyV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentWithKeyV2(key GetMultipleContentsRequest1RequestedKeysInner, content Content5) *ContentWithKeyV2 {
	this := ContentWithKeyV2{}
	this.Key = key
	this.Content = content
	return &this
}

// NewContentWithKeyV2WithDefaults instantiates a new ContentWithKeyV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentWithKeyV2WithDefaults() *ContentWithKeyV2 {
	this := ContentWithKeyV2{}
	return &this
}

// GetKey returns the Key field value
func (o *ContentWithKeyV2) GetKey() GetMultipleContentsRequest1RequestedKeysInner {
	if o == nil {
		var ret GetMultipleContentsRequest1RequestedKeysInner
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ContentWithKeyV2) GetKeyOk() (*GetMultipleContentsRequest1RequestedKeysInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ContentWithKeyV2) SetKey(v GetMultipleContentsRequest1RequestedKeysInner) {
	o.Key = v
}

// GetContent returns the Content field value
func (o *ContentWithKeyV2) GetContent() Content5 {
	if o == nil {
		var ret Content5
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ContentWithKeyV2) GetContentOk() (*Content5, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ContentWithKeyV2) SetContent(v Content5) {
	o.Content = v
}

// GetDocumentation returns the Documentation field value if set, zero value otherwise.
func (o *ContentWithKeyV2) GetDocumentation() PutContentOperationForAContentKeyDocumentation {
	if o == nil || IsNil(o.Documentation) {
		var ret PutContentOperationForAContentKeyDocumentation
		return ret
	}
	return *o.Documentation
}

// GetDocumentationOk returns a tuple with the Documentation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentWithKeyV2) GetDocumentationOk() (*PutContentOperationForAContentKeyDocumentation, bool) {
	if o == nil || IsNil(o.Documentation) {
		return nil, false
	}
	return o.Documentation, true
}

// HasDocumentation returns a boolean if a field has been set.
func (o *ContentWithKeyV2) HasDocumentation() bool {
	if o != nil && !IsNil(o.Documentation) {
		return true
	}

	return false
}

// SetDocumentation gets a reference to the given PutContentOperationForAContentKeyDocumentation and assigns it to the Documentation field.
func (o *ContentWithKeyV2) SetDocumentation(v PutContentOperationForAContentKeyDocumentation) {
	o.Documentation = &v
}

func (o ContentWithKeyV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentWithKeyV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["content"] = o.Content
	if !IsNil(o.Documentation) {
		toSerialize["documentation"] = o.Documentation
	}
	return toSerialize, nil
}

func (o *ContentWithKeyV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContentWithKeyV2 := _ContentWithKeyV2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContentWithKeyV2)

	if err != nil {
		return err
	}

	*o = ContentWithKeyV2(varContentWithKeyV2)

	return err
}

type NullableContentWithKeyV2 struct {
	value *ContentWithKeyV2
	isSet bool
}

func (v NullableContentWithKeyV2) Get() *ContentWithKeyV2 {
	return v.value
}

func (v *NullableContentWithKeyV2) Set(val *ContentWithKeyV2) {
	v.value = val
	v.isSet = true
}

func (v NullableContentWithKeyV2) IsSet() bool {
	return v.isSet
}

func (v *NullableContentWithKeyV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentWithKeyV2(val *ContentWithKeyV2) *NullableContentWithKeyV2 {
	return &NullableContentWithKeyV2{value: val, isSet: true}
}

func (v NullableContentWithKeyV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentWithKeyV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


