/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// Reference - struct for Reference
type Reference struct {
	Branch2 *Branch2
	DetachedCommitHash1 *DetachedCommitHash1
	Tag2 *Tag2
}

// Branch2AsReference is a convenience function that returns Branch2 wrapped in Reference
func Branch2AsReference(v *Branch2) Reference {
	return Reference{
		Branch2: v,
	}
}

// DetachedCommitHash1AsReference is a convenience function that returns DetachedCommitHash1 wrapped in Reference
func DetachedCommitHash1AsReference(v *DetachedCommitHash1) Reference {
	return Reference{
		DetachedCommitHash1: v,
	}
}

// Tag2AsReference is a convenience function that returns Tag2 wrapped in Reference
func Tag2AsReference(v *Tag2) Reference {
	return Reference{
		Tag2: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Reference) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Branch2
	err = newStrictDecoder(data).Decode(&dst.Branch2)
	if err == nil {
		jsonBranch2, _ := json.Marshal(dst.Branch2)
		if string(jsonBranch2) == "{}" { // empty struct
			dst.Branch2 = nil
		} else {
			if err = validator.Validate(dst.Branch2); err != nil {
				dst.Branch2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Branch2 = nil
	}

	// try to unmarshal data into DetachedCommitHash1
	err = newStrictDecoder(data).Decode(&dst.DetachedCommitHash1)
	if err == nil {
		jsonDetachedCommitHash1, _ := json.Marshal(dst.DetachedCommitHash1)
		if string(jsonDetachedCommitHash1) == "{}" { // empty struct
			dst.DetachedCommitHash1 = nil
		} else {
			if err = validator.Validate(dst.DetachedCommitHash1); err != nil {
				dst.DetachedCommitHash1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.DetachedCommitHash1 = nil
	}

	// try to unmarshal data into Tag2
	err = newStrictDecoder(data).Decode(&dst.Tag2)
	if err == nil {
		jsonTag2, _ := json.Marshal(dst.Tag2)
		if string(jsonTag2) == "{}" { // empty struct
			dst.Tag2 = nil
		} else {
			if err = validator.Validate(dst.Tag2); err != nil {
				dst.Tag2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Tag2 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Branch2 = nil
		dst.DetachedCommitHash1 = nil
		dst.Tag2 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Reference)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Reference)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Reference) MarshalJSON() ([]byte, error) {
	if src.Branch2 != nil {
		return json.Marshal(&src.Branch2)
	}

	if src.DetachedCommitHash1 != nil {
		return json.Marshal(&src.DetachedCommitHash1)
	}

	if src.Tag2 != nil {
		return json.Marshal(&src.Tag2)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Reference) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Branch2 != nil {
		return obj.Branch2
	}

	if obj.DetachedCommitHash1 != nil {
		return obj.DetachedCommitHash1
	}

	if obj.Tag2 != nil {
		return obj.Tag2
	}

	// all schemas are nil
	return nil
}

type NullableReference struct {
	value *Reference
	isSet bool
}

func (v NullableReference) Get() *Reference {
	return v.value
}

func (v *NullableReference) Set(val *Reference) {
	v.value = val
	v.isSet = true
}

func (v NullableReference) IsSet() bool {
	return v.isSet
}

func (v *NullableReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReference(val *Reference) *NullableReference {
	return &NullableReference{value: val, isSet: true}
}

func (v NullableReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


