/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LogResponseV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogResponseV1{}

// LogResponseV1 struct for LogResponseV1
type LogResponseV1 struct {
	HasMore *bool `json:"hasMore,omitempty"`
	Token *string `json:"token,omitempty"`
	LogEntries []LogEntry1 `json:"logEntries"`
}

type _LogResponseV1 LogResponseV1

// NewLogResponseV1 instantiates a new LogResponseV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogResponseV1(logEntries []LogEntry1) *LogResponseV1 {
	this := LogResponseV1{}
	this.LogEntries = logEntries
	return &this
}

// NewLogResponseV1WithDefaults instantiates a new LogResponseV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogResponseV1WithDefaults() *LogResponseV1 {
	this := LogResponseV1{}
	return &this
}

// GetHasMore returns the HasMore field value if set, zero value otherwise.
func (o *LogResponseV1) GetHasMore() bool {
	if o == nil || IsNil(o.HasMore) {
		var ret bool
		return ret
	}
	return *o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseV1) GetHasMoreOk() (*bool, bool) {
	if o == nil || IsNil(o.HasMore) {
		return nil, false
	}
	return o.HasMore, true
}

// HasHasMore returns a boolean if a field has been set.
func (o *LogResponseV1) HasHasMore() bool {
	if o != nil && !IsNil(o.HasMore) {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given bool and assigns it to the HasMore field.
func (o *LogResponseV1) SetHasMore(v bool) {
	o.HasMore = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *LogResponseV1) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseV1) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *LogResponseV1) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *LogResponseV1) SetToken(v string) {
	o.Token = &v
}

// GetLogEntries returns the LogEntries field value
func (o *LogResponseV1) GetLogEntries() []LogEntry1 {
	if o == nil {
		var ret []LogEntry1
		return ret
	}

	return o.LogEntries
}

// GetLogEntriesOk returns a tuple with the LogEntries field value
// and a boolean to check if the value has been set.
func (o *LogResponseV1) GetLogEntriesOk() ([]LogEntry1, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogEntries, true
}

// SetLogEntries sets field value
func (o *LogResponseV1) SetLogEntries(v []LogEntry1) {
	o.LogEntries = v
}

func (o LogResponseV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LogResponseV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HasMore) {
		toSerialize["hasMore"] = o.HasMore
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	toSerialize["logEntries"] = o.LogEntries
	return toSerialize, nil
}

func (o *LogResponseV1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"logEntries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLogResponseV1 := _LogResponseV1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLogResponseV1)

	if err != nil {
		return err
	}

	*o = LogResponseV1(varLogResponseV1)

	return err
}

type NullableLogResponseV1 struct {
	value *LogResponseV1
	isSet bool
}

func (v NullableLogResponseV1) Get() *LogResponseV1 {
	return v.value
}

func (v *NullableLogResponseV1) Set(val *LogResponseV1) {
	v.value = val
	v.isSet = true
}

func (v NullableLogResponseV1) IsSet() bool {
	return v.isSet
}

func (v *NullableLogResponseV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogResponseV1(val *LogResponseV1) *NullableLogResponseV1 {
	return &NullableLogResponseV1{value: val, isSet: true}
}

func (v NullableLogResponseV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogResponseV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


