/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PutV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutV1{}

// PutV1 Used to add new content or to update existing content.  A new content object is created by populating the `value` field, the content-id in the content object must not be present (null).  A content object is updated by populating the `value` containing the correct content-id.  If the key for a content shall change (aka a rename), then use a `Delete` operation using the current (old) key and a `Put` operation using the new key with the `value` having the correct content-id. Both operations must happen in the same commit.  A content object can be replaced (think: `DROP TABLE xyz` + `CREATE TABLE xyz`) with a `Delete` operation and a `Put` operation for a content using a `value`representing a new content object, so without a content-id, in the same commit.
type PutV1 struct {
	Key GetMultipleContentsRequest1RequestedKeysInner `json:"key"`
	Content Content1 `json:"content"`
	// Deprecated
	ExpectedContent *Content4 `json:"expectedContent,omitempty"`
}

type _PutV1 PutV1

// NewPutV1 instantiates a new PutV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutV1(key GetMultipleContentsRequest1RequestedKeysInner, content Content1) *PutV1 {
	this := PutV1{}
	this.Key = key
	this.Content = content
	return &this
}

// NewPutV1WithDefaults instantiates a new PutV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutV1WithDefaults() *PutV1 {
	this := PutV1{}
	return &this
}

// GetKey returns the Key field value
func (o *PutV1) GetKey() GetMultipleContentsRequest1RequestedKeysInner {
	if o == nil {
		var ret GetMultipleContentsRequest1RequestedKeysInner
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *PutV1) GetKeyOk() (*GetMultipleContentsRequest1RequestedKeysInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *PutV1) SetKey(v GetMultipleContentsRequest1RequestedKeysInner) {
	o.Key = v
}

// GetContent returns the Content field value
func (o *PutV1) GetContent() Content1 {
	if o == nil {
		var ret Content1
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *PutV1) GetContentOk() (*Content1, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *PutV1) SetContent(v Content1) {
	o.Content = v
}

// GetExpectedContent returns the ExpectedContent field value if set, zero value otherwise.
// Deprecated
func (o *PutV1) GetExpectedContent() Content4 {
	if o == nil || IsNil(o.ExpectedContent) {
		var ret Content4
		return ret
	}
	return *o.ExpectedContent
}

// GetExpectedContentOk returns a tuple with the ExpectedContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *PutV1) GetExpectedContentOk() (*Content4, bool) {
	if o == nil || IsNil(o.ExpectedContent) {
		return nil, false
	}
	return o.ExpectedContent, true
}

// HasExpectedContent returns a boolean if a field has been set.
func (o *PutV1) HasExpectedContent() bool {
	if o != nil && !IsNil(o.ExpectedContent) {
		return true
	}

	return false
}

// SetExpectedContent gets a reference to the given Content4 and assigns it to the ExpectedContent field.
// Deprecated
func (o *PutV1) SetExpectedContent(v Content4) {
	o.ExpectedContent = &v
}

func (o PutV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["content"] = o.Content
	if !IsNil(o.ExpectedContent) {
		toSerialize["expectedContent"] = o.ExpectedContent
	}
	return toSerialize, nil
}

func (o *PutV1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPutV1 := _PutV1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPutV1)

	if err != nil {
		return err
	}

	*o = PutV1(varPutV1)

	return err
}

type NullablePutV1 struct {
	value *PutV1
	isSet bool
}

func (v NullablePutV1) Get() *PutV1 {
	return v.value
}

func (v *NullablePutV1) Set(val *PutV1) {
	v.value = val
	v.isSet = true
}

func (v NullablePutV1) IsSet() bool {
	return v.isSet
}

func (v *NullablePutV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutV1(val *PutV1) *NullablePutV1 {
	return &NullablePutV1{value: val, isSet: true}
}

func (v NullablePutV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


