/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Transplant2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Transplant2{}

// Transplant2 struct for Transplant2
type Transplant2 struct {
	// Commit message for this transplant request.
	Message *string `json:"message,omitempty"`
	// Lists the hashes of commits that should be transplanted into the target branch.
	HashesToTransplant []string `json:"hashesToTransplant"`
	// The name of the reference that contains the 'source' commits for the requested merge or transplant operation. 
	FromRefName string `json:"fromRefName" validate:"regexp=^(?:[A-Za-z](?:(?:(?![.][.])[A-Za-z0-9.\\/_-])*[A-Za-z0-9_-])?)|-$"`
	// Specific merge behaviour requests by content key.  The default is set by the `defaultKeyMergeMode` parameter. 
	KeyMergeModes []MergeOperationKeyMergeModesInner `json:"keyMergeModes,omitempty"`
	// The default merge mode. If not set, `NORMAL` is assumed.  This settings applies to key thaWhen set to 'true' instructs the server to validate the request but to avoid committing any changes.t are not explicitly mentioned in the `keyMergeModes` property. 
	DefaultKeyMergeMode *string `json:"defaultKeyMergeMode,omitempty"`
	// When set to 'true' instructs the server to validate the request but to avoid committing any changes. 
	DryRun *bool `json:"dryRun,omitempty"`
	// Whether to provide optional response data. 
	FetchAdditionalInfo *bool `json:"fetchAdditionalInfo,omitempty"`
	// When set to 'true' instructs the server to produce normal (non-error) responses in case a conflict is detected and report conflict details in the response payload.
	ReturnConflictAsResult *bool `json:"returnConflictAsResult,omitempty"`
}

type _Transplant2 Transplant2

// NewTransplant2 instantiates a new Transplant2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransplant2(hashesToTransplant []string, fromRefName string) *Transplant2 {
	this := Transplant2{}
	this.HashesToTransplant = hashesToTransplant
	this.FromRefName = fromRefName
	return &this
}

// NewTransplant2WithDefaults instantiates a new Transplant2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransplant2WithDefaults() *Transplant2 {
	this := Transplant2{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Transplant2) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transplant2) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Transplant2) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Transplant2) SetMessage(v string) {
	o.Message = &v
}

// GetHashesToTransplant returns the HashesToTransplant field value
func (o *Transplant2) GetHashesToTransplant() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.HashesToTransplant
}

// GetHashesToTransplantOk returns a tuple with the HashesToTransplant field value
// and a boolean to check if the value has been set.
func (o *Transplant2) GetHashesToTransplantOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HashesToTransplant, true
}

// SetHashesToTransplant sets field value
func (o *Transplant2) SetHashesToTransplant(v []string) {
	o.HashesToTransplant = v
}

// GetFromRefName returns the FromRefName field value
func (o *Transplant2) GetFromRefName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromRefName
}

// GetFromRefNameOk returns a tuple with the FromRefName field value
// and a boolean to check if the value has been set.
func (o *Transplant2) GetFromRefNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromRefName, true
}

// SetFromRefName sets field value
func (o *Transplant2) SetFromRefName(v string) {
	o.FromRefName = v
}

// GetKeyMergeModes returns the KeyMergeModes field value if set, zero value otherwise.
func (o *Transplant2) GetKeyMergeModes() []MergeOperationKeyMergeModesInner {
	if o == nil || IsNil(o.KeyMergeModes) {
		var ret []MergeOperationKeyMergeModesInner
		return ret
	}
	return o.KeyMergeModes
}

// GetKeyMergeModesOk returns a tuple with the KeyMergeModes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transplant2) GetKeyMergeModesOk() ([]MergeOperationKeyMergeModesInner, bool) {
	if o == nil || IsNil(o.KeyMergeModes) {
		return nil, false
	}
	return o.KeyMergeModes, true
}

// HasKeyMergeModes returns a boolean if a field has been set.
func (o *Transplant2) HasKeyMergeModes() bool {
	if o != nil && !IsNil(o.KeyMergeModes) {
		return true
	}

	return false
}

// SetKeyMergeModes gets a reference to the given []MergeOperationKeyMergeModesInner and assigns it to the KeyMergeModes field.
func (o *Transplant2) SetKeyMergeModes(v []MergeOperationKeyMergeModesInner) {
	o.KeyMergeModes = v
}

// GetDefaultKeyMergeMode returns the DefaultKeyMergeMode field value if set, zero value otherwise.
func (o *Transplant2) GetDefaultKeyMergeMode() string {
	if o == nil || IsNil(o.DefaultKeyMergeMode) {
		var ret string
		return ret
	}
	return *o.DefaultKeyMergeMode
}

// GetDefaultKeyMergeModeOk returns a tuple with the DefaultKeyMergeMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transplant2) GetDefaultKeyMergeModeOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultKeyMergeMode) {
		return nil, false
	}
	return o.DefaultKeyMergeMode, true
}

// HasDefaultKeyMergeMode returns a boolean if a field has been set.
func (o *Transplant2) HasDefaultKeyMergeMode() bool {
	if o != nil && !IsNil(o.DefaultKeyMergeMode) {
		return true
	}

	return false
}

// SetDefaultKeyMergeMode gets a reference to the given string and assigns it to the DefaultKeyMergeMode field.
func (o *Transplant2) SetDefaultKeyMergeMode(v string) {
	o.DefaultKeyMergeMode = &v
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *Transplant2) GetDryRun() bool {
	if o == nil || IsNil(o.DryRun) {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transplant2) GetDryRunOk() (*bool, bool) {
	if o == nil || IsNil(o.DryRun) {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *Transplant2) HasDryRun() bool {
	if o != nil && !IsNil(o.DryRun) {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *Transplant2) SetDryRun(v bool) {
	o.DryRun = &v
}

// GetFetchAdditionalInfo returns the FetchAdditionalInfo field value if set, zero value otherwise.
func (o *Transplant2) GetFetchAdditionalInfo() bool {
	if o == nil || IsNil(o.FetchAdditionalInfo) {
		var ret bool
		return ret
	}
	return *o.FetchAdditionalInfo
}

// GetFetchAdditionalInfoOk returns a tuple with the FetchAdditionalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transplant2) GetFetchAdditionalInfoOk() (*bool, bool) {
	if o == nil || IsNil(o.FetchAdditionalInfo) {
		return nil, false
	}
	return o.FetchAdditionalInfo, true
}

// HasFetchAdditionalInfo returns a boolean if a field has been set.
func (o *Transplant2) HasFetchAdditionalInfo() bool {
	if o != nil && !IsNil(o.FetchAdditionalInfo) {
		return true
	}

	return false
}

// SetFetchAdditionalInfo gets a reference to the given bool and assigns it to the FetchAdditionalInfo field.
func (o *Transplant2) SetFetchAdditionalInfo(v bool) {
	o.FetchAdditionalInfo = &v
}

// GetReturnConflictAsResult returns the ReturnConflictAsResult field value if set, zero value otherwise.
func (o *Transplant2) GetReturnConflictAsResult() bool {
	if o == nil || IsNil(o.ReturnConflictAsResult) {
		var ret bool
		return ret
	}
	return *o.ReturnConflictAsResult
}

// GetReturnConflictAsResultOk returns a tuple with the ReturnConflictAsResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transplant2) GetReturnConflictAsResultOk() (*bool, bool) {
	if o == nil || IsNil(o.ReturnConflictAsResult) {
		return nil, false
	}
	return o.ReturnConflictAsResult, true
}

// HasReturnConflictAsResult returns a boolean if a field has been set.
func (o *Transplant2) HasReturnConflictAsResult() bool {
	if o != nil && !IsNil(o.ReturnConflictAsResult) {
		return true
	}

	return false
}

// SetReturnConflictAsResult gets a reference to the given bool and assigns it to the ReturnConflictAsResult field.
func (o *Transplant2) SetReturnConflictAsResult(v bool) {
	o.ReturnConflictAsResult = &v
}

func (o Transplant2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Transplant2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	toSerialize["hashesToTransplant"] = o.HashesToTransplant
	toSerialize["fromRefName"] = o.FromRefName
	if !IsNil(o.KeyMergeModes) {
		toSerialize["keyMergeModes"] = o.KeyMergeModes
	}
	if !IsNil(o.DefaultKeyMergeMode) {
		toSerialize["defaultKeyMergeMode"] = o.DefaultKeyMergeMode
	}
	if !IsNil(o.DryRun) {
		toSerialize["dryRun"] = o.DryRun
	}
	if !IsNil(o.FetchAdditionalInfo) {
		toSerialize["fetchAdditionalInfo"] = o.FetchAdditionalInfo
	}
	if !IsNil(o.ReturnConflictAsResult) {
		toSerialize["returnConflictAsResult"] = o.ReturnConflictAsResult
	}
	return toSerialize, nil
}

func (o *Transplant2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hashesToTransplant",
		"fromRefName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransplant2 := _Transplant2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransplant2)

	if err != nil {
		return err
	}

	*o = Transplant2(varTransplant2)

	return err
}

type NullableTransplant2 struct {
	value *Transplant2
	isSet bool
}

func (v NullableTransplant2) Get() *Transplant2 {
	return v.value
}

func (v *NullableTransplant2) Set(val *Transplant2) {
	v.value = val
	v.isSet = true
}

func (v NullableTransplant2) IsSet() bool {
	return v.isSet
}

func (v *NullableTransplant2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransplant2(val *Transplant2) *NullableTransplant2 {
	return &NullableTransplant2{value: val, isSet: true}
}

func (v NullableTransplant2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransplant2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


