/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// Operation - Describes an operation to be performed against one content object.  The Nessie backend will validate the correctness of the operations.
type Operation struct {
	DeleteContentOperationForAContentKey *DeleteContentOperationForAContentKey
	Operation1OneOf *Operation1OneOf
	PutContentOperationForAContentKey3 *PutContentOperationForAContentKey3
}

// DeleteContentOperationForAContentKeyAsOperation is a convenience function that returns DeleteContentOperationForAContentKey wrapped in Operation
func DeleteContentOperationForAContentKeyAsOperation(v *DeleteContentOperationForAContentKey) Operation {
	return Operation{
		DeleteContentOperationForAContentKey: v,
	}
}

// Operation1OneOfAsOperation is a convenience function that returns Operation1OneOf wrapped in Operation
func Operation1OneOfAsOperation(v *Operation1OneOf) Operation {
	return Operation{
		Operation1OneOf: v,
	}
}

// PutContentOperationForAContentKey3AsOperation is a convenience function that returns PutContentOperationForAContentKey3 wrapped in Operation
func PutContentOperationForAContentKey3AsOperation(v *PutContentOperationForAContentKey3) Operation {
	return Operation{
		PutContentOperationForAContentKey3: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Operation) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into DeleteContentOperationForAContentKey
	err = newStrictDecoder(data).Decode(&dst.DeleteContentOperationForAContentKey)
	if err == nil {
		jsonDeleteContentOperationForAContentKey, _ := json.Marshal(dst.DeleteContentOperationForAContentKey)
		if string(jsonDeleteContentOperationForAContentKey) == "{}" { // empty struct
			dst.DeleteContentOperationForAContentKey = nil
		} else {
			if err = validator.Validate(dst.DeleteContentOperationForAContentKey); err != nil {
				dst.DeleteContentOperationForAContentKey = nil
			} else {
				match++
			}
		}
	} else {
		dst.DeleteContentOperationForAContentKey = nil
	}

	// try to unmarshal data into Operation1OneOf
	err = newStrictDecoder(data).Decode(&dst.Operation1OneOf)
	if err == nil {
		jsonOperation1OneOf, _ := json.Marshal(dst.Operation1OneOf)
		if string(jsonOperation1OneOf) == "{}" { // empty struct
			dst.Operation1OneOf = nil
		} else {
			if err = validator.Validate(dst.Operation1OneOf); err != nil {
				dst.Operation1OneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.Operation1OneOf = nil
	}

	// try to unmarshal data into PutContentOperationForAContentKey3
	err = newStrictDecoder(data).Decode(&dst.PutContentOperationForAContentKey3)
	if err == nil {
		jsonPutContentOperationForAContentKey3, _ := json.Marshal(dst.PutContentOperationForAContentKey3)
		if string(jsonPutContentOperationForAContentKey3) == "{}" { // empty struct
			dst.PutContentOperationForAContentKey3 = nil
		} else {
			if err = validator.Validate(dst.PutContentOperationForAContentKey3); err != nil {
				dst.PutContentOperationForAContentKey3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.PutContentOperationForAContentKey3 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.DeleteContentOperationForAContentKey = nil
		dst.Operation1OneOf = nil
		dst.PutContentOperationForAContentKey3 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Operation)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Operation)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Operation) MarshalJSON() ([]byte, error) {
	if src.DeleteContentOperationForAContentKey != nil {
		return json.Marshal(&src.DeleteContentOperationForAContentKey)
	}

	if src.Operation1OneOf != nil {
		return json.Marshal(&src.Operation1OneOf)
	}

	if src.PutContentOperationForAContentKey3 != nil {
		return json.Marshal(&src.PutContentOperationForAContentKey3)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Operation) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.DeleteContentOperationForAContentKey != nil {
		return obj.DeleteContentOperationForAContentKey
	}

	if obj.Operation1OneOf != nil {
		return obj.Operation1OneOf
	}

	if obj.PutContentOperationForAContentKey3 != nil {
		return obj.PutContentOperationForAContentKey3
	}

	// all schemas are nil
	return nil
}

type NullableOperation struct {
	value *Operation
	isSet bool
}

func (v NullableOperation) Get() *Operation {
	return v.value
}

func (v *NullableOperation) Set(val *Operation) {
	v.value = val
	v.isSet = true
}

func (v NullableOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperation(val *Operation) *NullableOperation {
	return &NullableOperation{value: val, isSet: true}
}

func (v NullableOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


