/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.102.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Detached type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Detached{}

// Detached struct for Detached
type Detached struct {
	Hash string `json:"hash" validate:"regexp=^([0-9a-fA-F]{8,64})?((?:([~*^])([0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{1,9}Z|([0-9]+)))*)$"`
	Metadata *ReferenceMetadata2 `json:"metadata,omitempty"`
}

type _Detached Detached

// NewDetached instantiates a new Detached object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetached(hash string) *Detached {
	this := Detached{}
	this.Hash = hash
	return &this
}

// NewDetachedWithDefaults instantiates a new Detached object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetachedWithDefaults() *Detached {
	this := Detached{}
	return &this
}

// GetHash returns the Hash field value
func (o *Detached) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *Detached) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *Detached) SetHash(v string) {
	o.Hash = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Detached) GetMetadata() ReferenceMetadata2 {
	if o == nil || IsNil(o.Metadata) {
		var ret ReferenceMetadata2
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Detached) GetMetadataOk() (*ReferenceMetadata2, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Detached) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given ReferenceMetadata2 and assigns it to the Metadata field.
func (o *Detached) SetMetadata(v ReferenceMetadata2) {
	o.Metadata = &v
}

func (o Detached) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Detached) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hash"] = o.Hash
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *Detached) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hash",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDetached := _Detached{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDetached)

	if err != nil {
		return err
	}

	*o = Detached(varDetached)

	return err
}

type NullableDetached struct {
	value *Detached
	isSet bool
}

func (v NullableDetached) Get() *Detached {
	return v.value
}

func (v *NullableDetached) Set(val *Detached) {
	v.value = val
	v.isSet = true
}

func (v NullableDetached) IsSet() bool {
	return v.isSet
}

func (v *NullableDetached) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetached(val *Detached) *NullableDetached {
	return &NullableDetached{value: val, isSet: true}
}

func (v NullableDetached) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetached) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


